[workspace]
authors = ["DiaaEddinH <diaaeddinh@gmail.com>"]
channels = ["conda-forge"]
name = "CCP-TEPP-SS-Docs"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
doxygen = ">=1.17.0,<2"
sphinx = ">=9.1.0,<10"
myst-parser = ">=5.1.0,<6"
